buffer:
  duration_seconds: 30
  fps: 10
dio:
  bit_a: 0
  bit_b: 1
  device_name: DIO000
  simulation_mode: false
save:
  base_directory: c:\Duy\GitHub\oin-wood-inspection\src-api\data\images\inspection
  format: jpg
  quality: 95
