// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  create_dt?: Date;
  update_dt?: Date;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Product = Entity<{
  product_no: string;
  product_name: string;
  file_path: string;
}>;

export type Inspection = Entity<{
  inspection_id: number;
  product_no: string;
  serial: string;
  inspection_dt: Date;
  inspection_result: boolean;
  file_path: string;
}>;

export type Datasets = Entity<{
  id: number;
  file_path: string;
  label: number;
}>;

export type ApiResult<T = never> = {
  result: boolean;
  message: string;
  total_count?: number;
  page_no?: number;
  page_size?: number;
} & (T extends never ? {} : { data: T });
