SET CHARACTER_SET_CLIENT = utf8mb4;
SET CHARACTER_SET_CONNECTION = utf8mb4;

DROP TABLE if exists t_product;
CREATE TABLE t_product (
  `product_no` VARCHAR(10) NOT NULL COMMENT '品番',
  `product_name` VARCHAR(50) NOT NULL COMMENT '品名',
  `file_path` VARCHAR(4096) COMMENT 'ファイルパス',
  `create_dt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `update_dt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  PRIMARY KEY (`product_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='製品テーブル';